services:
  frontend:
    image: stivenc30/cropco-frontend:latest
    container_name: frontend-container
    ports:
      - 8081:80
    environment:
      - VITE_HOST_API_CROPCO:http://localhost:3000/
      - VITE_STATUS_PROJECT:development
      - PORT:8081
    depends_on:
      - backend
  backend:
    image: stivenc30/cropco-api-rest:latest
    container_name: backend-container
    ports:
      - 3000:3000
    environment:
      - DB_HOST=server-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_NAME=cropco
      - JWT_SECRET=millavesecreta
      - PORT=3000
      - HOST_FRONTED=https://cropco.netlify.app
      - DB_CA_CERT_PATH=certs/ca-certificate.crt
      - STATUS_PROJECT=development
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: server-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cropco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    volumes:
      - ./data-server-db-development:/var/lib/postgresql/data
    restart: always
