services:
  frontend:
    image: stivenc30/cropco-frontend:multi-tenant
    container_name: frontend-container-multi-tenant
    ports:
      - ${VITE_PORT_FRONTEND_CONTAINER}:80
    environment:
      - VITE_HOST_API_CROPCO=${VITE_HOST_API_CROPCO}
      - VITE_STATUS_PROJECT=${VITE_STATUS_PROJECT}
    depends_on:
      - backend
  backend:
    image: stivenc30/public-cropco-api-rest:multi-tenant
    container_name: backend-container-multi-tenant
    ports:
      - ${PORT_BACKEND_CONTAINER}:${PORT_BACKEND}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - PORT_BACKEND=${PORT_BACKEND}
      - HOST_FRONTED=${HOST_FRONTED}
      - DB_CA_CERT_PATH=${DB_CA_CERT_PATH}
      - STATUS_PROJECT=${STATUS_PROJECT}
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: server-db-cropco-multi-tenant
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data-server-db-cropco:/var/lib/postgresql/data
    restart: always
volumes:
  data-server-db-cropco:
