services:
  frontend:
    image: stivenc30/cropco-frontend:latest
    # image: cropco-frontend:local
    container_name: frontend-container
    ports:
      - ${VITE_PORT_FRONTEND_CONTAINER}:80
    environment:
      # - VITE_HOST_API_CROPCO=http://localhost:3001/
      # - VITE_STATUS_PROJECT=development
      - VITE_HOST_API_CROPCO=${VITE_HOST_API_CROPCO}
      - VITE_STATUS_PROJECT=${VITE_STATUS_PROJECT}
    depends_on:
      - backend
  backend:
    image: stivenc30/cropco-api-rest:latest
    # image: cropco-api-rest:latest
    container_name: backend-container
    ports:
      - ${PORT_BACKEND_CONTAINER}:3000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - PORT_BACKEND=${PORT_BACKEND}
      - HOST_FRONTED=${HOST_FRONTED}
      - DB_CA_CERT_PATH=${DB_CA_CERT_PATH}
      - STATUS_PROJECT=${STATUS_PROJECT}
    # depends_on:
    #   - db
  # db:
  #   image: postgres:15
  #   container_name: server-db
  #   ports:
  #     - '${DB_PORT}:5432'
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - ./data-server-db-development:/var/lib/postgresql/data
  #   restart: always
